// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxpGl3QAlEHal-4JDsW3sJDnJ_BzG0I7Y',
    appId: '1:806648232051:web:85ad65b242660d4dc95206',
    messagingSenderId: '806648232051',
    projectId: 'hair-art-salon',
    authDomain: 'hair-art-salon.firebaseapp.com',
    storageBucket: 'hair-art-salon.firebasestorage.app',
    measurementId: 'G-XY3WQ0VFSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAQKLfLOk3yQPTDPRkDXyJGM68TDHodS8',
    appId: '1:806648232051:android:8e2535f87f5e99c5c95206',
    messagingSenderId: '806648232051',
    projectId: 'hair-art-salon',
    storageBucket: 'hair-art-salon.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3Lb2P2Mpka1vCON9zb0U7TeYwemC09b0',
    appId: '1:806648232051:ios:c2675b70dea98bd5c95206',
    messagingSenderId: '806648232051',
    projectId: 'hair-art-salon',
    storageBucket: 'hair-art-salon.firebasestorage.app',
    androidClientId: '806648232051-615o39vr4ac465trj2egnmou9ucacor9.apps.googleusercontent.com',
    iosClientId: '806648232051-5o9905v94jguijg24mfmo0krup0h16cq.apps.googleusercontent.com',
    iosBundleId: 'com.example.hairArtSalon',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3Lb2P2Mpka1vCON9zb0U7TeYwemC09b0',
    appId: '1:806648232051:ios:c2675b70dea98bd5c95206',
    messagingSenderId: '806648232051',
    projectId: 'hair-art-salon',
    storageBucket: 'hair-art-salon.firebasestorage.app',
    androidClientId: '806648232051-615o39vr4ac465trj2egnmou9ucacor9.apps.googleusercontent.com',
    iosClientId: '806648232051-5o9905v94jguijg24mfmo0krup0h16cq.apps.googleusercontent.com',
    iosBundleId: 'com.example.hairArtSalon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxpGl3QAlEHal-4JDsW3sJDnJ_BzG0I7Y',
    appId: '1:806648232051:web:ab7c622bd17af247c95206',
    messagingSenderId: '806648232051',
    projectId: 'hair-art-salon',
    authDomain: 'hair-art-salon.firebaseapp.com',
    storageBucket: 'hair-art-salon.firebasestorage.app',
    measurementId: 'G-BBPP69T5PX',
  );
}
